version = 0.1

[default.deploy.parameters]
stack_name = "dropbex-stack"
resolve_s3 = true
s3_prefix = "dropbex-stack"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AppName=\"dropbex-app-2025\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
