version = 0.1


[default]
[default.global.parameters]

stack_name = "dropbex-mvp"


region = "us-east-1"

[default.deploy.parameters]


confirm_changeset = true


capabilities = "CAPABILITY_IAM"


resolve_s3 = true


s3_prefix = "dropbex-mvp"

image_repositories = []
disable_rollback = true

